apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: react-microk8s
spec:
  type: NodePort #remove the NodePort in case you choose to deploy Kubernetes application with Domain
  selector:
    app: react-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32720  #remove the NodePort in case you choose to deploy Kubernetes application with Domain
